export const bestsellers = [
  {
    src: '/imgs/iPhone16.png',
    title: 'Apple iPhone 16',
    description:
      'Flagship smartphone with A16 Bionic chip, expansive OLED display, and advanced camera system.',
    deliveryPeriod: '1–2 days',
    specs: [
      'A16 Bionic 6-core CPU',
      '6.7" Super Retina XDR OLED',
      '128 GB / 256 GB storage options',
      '48 MP main camera with Night mode',
      '5G, Wi-Fi 6, Bluetooth 5.3',
      'Face ID and MagSafe charging',
    ],
    slashedPrice: '1700000',
    // discountPercent: null,
    price: '1220000',
    rating: 4,
  },
  {
    src: '/imgs/ps5.png',
    title: 'PS5 Game Console',
    description:
      'Next-gen gaming console delivering ultra-high-speed SSD loading and stunning visuals.',
    deliveryPeriod: '2–4 days',
    specs: [
      'Custom AMD Ryzen Zen 2 8-core CPU',
      'Custom AMD RDNA 2 GPU (10.28 TFLOPs)',
      '825 GB NVMe SSD',
      'Up to 8K output, 4K/120 Hz support',
      'DualSense wireless controller',
      'Tempest 3D AudioTech',
    ],
    slashedPrice: '900000',
    // discountPercent: null,
    price: '720000',
    rating: 5,
  },
  {
    src: '/imgs/jblhead.png',
    title: 'JBL Headset',
    description:
      'Wireless over-ear headset featuring active noise cancellation and rich JBL audio.',
    deliveryPeriod: '1–3 days',
    specs: [
      'Bluetooth 5.0 connectivity',
      'Active Noise Cancelling (ANC)',
      'Up to 20 hours battery life',
      'Foldable design for portability',
      'Built-in microphone for calls',
      'Comfort-fit ear cushions',
    ],
    slashedPrice: '100000',
    // discountPercent: null,
    price: '70000',
    rating: 4,
  },
  {
    src: '/imgs/watchX6Pro.png',
    title: 'Smartwatch X6Pro',
    description:
      'Feature-rich smartwatch with health tracking, GPS, and long battery life.',
    deliveryPeriod: '1–2 days',
    specs: [
      '1.78" AMOLED touchscreen',
      'Heart rate & SpO₂ monitoring',
      'Built-in GPS & GLONASS',
      'Sleep and stress tracking',
      'Up to 7 days battery life',
      'IP68 water & dust resistance',
    ],
    slashedPrice: '300000',
    // discountPercent: null,
    price: '220000',
    rating: 4,
  },
];
