export const flashsalesData = [
  {
    src: '/imgs/iPhone12promax.png',
    title: 'Apple IPhone 12 Pro Max',
    slashedPrice: '700000',
    discountPercent: '-40%',
    price: '420000',
    rating: 4,
  },
  {
    src: '/imgs/keyboard.png',
    title: 'AK-900 Wired Keyboard',
    slashedPrice: '12000',
    discountPercent: '-35%',
    price: '7800',
    rating: 3,
  },
  {
    src: '/imgs/mcbookair.png',
    title: 'Apple MacBook Air',
    slashedPrice: '870000',
    discountPercent: '-30%',
    price: '609000',
    rating: 4,
  },
  {
    src: '/imgs/iPhone11.png',
    title: 'Apple IPhone 11',
    slashedPrice: '500000',
    discountPercent: '-25%',
    price: '375000',
    rating: 2,
  },
  {
    src: '/imgs/pad.png',
    title: 'HAVIT HV-G92 Gamepad',
    slashedPrice: '14000',
    discountPercent: '-40%',
    price: '8400',
    rating: 4,
  },
  {
    src: '/imgs/redmi.png',
    title: 'Redmi Note 13',
    slashedPrice: '400000',
    discountPercent: '-35%',
    price: '260000',
    rating: 3,
  },
  {
    src: '/imgs/tv.png',
    title: 'IPS LCD Gaming Monitor',
    slashedPrice: '150000',
    discountPercent: '-30%',
    price: '105000',
    rating: 4,
  },
  {
    src: '/imgs/iPhonexr.png',
    title: 'Apple IPhone XR',
    slashedPrice: '350000',
    discountPercent: '-25%',
    price: '262500',
    rating: 2,
  },
];
