export const flashsalesData = [
  {
    src: '/imgs/iPhone12promax.png',
    title: 'Apple IPhone 12 Pro Max',
    slashedPrice: '700,000',
    discountPercent: '40%',
    price: '420,000',
    rating: 4,
  },
  {
    src: '/imgs/keyboard.png',
    title: 'AK-900 Wired Keyboard',
    slashedPrice: '12,000',
    discountPercent: '35%',
    price: '7,800',
    rating: 3,
  },
  {
    src: '/imgs/mcbookair.png',
    title: 'Apple MacBook Air',
    slashedPrice: '870,000',
    discountPercent: '30%',
    price: '609,000',
    rating: 4,
  },
  {
    src: '/imgs/iPhone11.png',
    title: 'Apple IPhone 11',
    slashedPrice: '500,000',
    discountPercent: '25%',
    price: '375,000',
    rating: 2,
  },
  {
    src: '/imgs/pad.png',
    title: 'HAVIT HV-G92 Gamepad',
    slashedPrice: '14,000',
    discountPercent: '40%',
    price: '8,400',
    rating: 4,
  },
  {
    src: '/imgs/redmi.png',
    title: 'Redmi Note 13',
    slashedPrice: '400,000',
    discountPercent: '35%',
    price: '260,000',
    rating: 3,
  },
  {
    src: '/imgs/tv.png',
    title: 'IPS LCD Gaming Monitor',
    slashedPrice: '150,000',
    discountPercent: '30%',
    price: '105,000',
    rating: 4,
  },
  {
    src: '/imgs/iPhonexr.png',
    title: 'Apple IPhone XR',
    slashedPrice: '350,000',
    discountPercent: '25%',
    price: '262,500',
    rating: 2,
  },
];
