export const products = [
  {
    src: '/imgs/xboxpad.png',
    title: 'Xbox Pad',
    description:
      'Ergonomic wireless controller for Xbox Series X/S and PC, with textured grip and responsive buttons.',
    deliveryPeriod: '1-2 days',
    specs: [
      'Wireless via Xbox Wireless and Bluetooth',
      'Built-in rechargeable battery (up to 30 hours runtime)',
      'Textured grip for better handling',
      '3.5mm stereo headset jack',
      'Custom button mapping',
    ],
    slashedPrice: '70000',
    discountPercent: '-10%',
    price: '64000',
    rating: 3,
  },
  {
    src: '/imgs/keyboard2.png',
    title: 'Wireless Keyboard',
    description:
      'Slim, compact 2.4GHz wireless keyboard with reliable connection and quiet, low-profile keys.',
    deliveryPeriod: '1-3 days',
    specs: [
      '2.4GHz USB receiver (plug-and-play)',
      '104-key layout with multimedia shortcuts',
      'Adjustable tilt legs',
      'Battery life up to 12 months (2× AAA)',
      'Spill-resistant design',
    ],
    slashedPrice: '12000',
    discountPercent: '-35%',
    price: '7800',
    rating: 3,
  },
  {
    src: '/imgs/asuslaptop.png',
    title: 'Asus Gaming laptop',
    description:
      'High-performance gaming laptop with Intel i7, NVIDIA RTX graphics, and fast SSD storage.',
    deliveryPeriod: '2-4 days',
    specs: [
      'Intel Core i7-12700H 14-core CPU',
      'NVIDIA GeForce RTX 3060 6 GB GDDR6',
      '16 GB DDR4 RAM (upgradeable)',
      '512 GB NVMe PCIe SSD',
      '15.6" FHD 144 Hz display',
      'RGB backlit keyboard',
      'Wi-Fi 6 and Bluetooth 5.2',
    ],
    slashedPrice: '470000',
    discountPercent: '-30%',
    price: '309000',
    rating: 3,
  },
  {
    src: '/imgs/jbl.png',
    title: 'JBL Speakers',
    description:
      'Portable Bluetooth speaker with deep bass, waterproof design, and long battery life.',
    deliveryPeriod: '1-2 days',
    specs: [
      'Bluetooth 5.1 connectivity',
      'Up to 12 hours of playtime',
      'IPX7 waterproof rating',
      'Built-in microphone for calls',
      'Wireless party boost (connect multiple speakers)',
    ],
    slashedPrice: '300000',
    discountPercent: '-15%',
    price: '275000',
    rating: 2,
  },
  {
    src: '/imgs/iPhone16.png',
    title: 'Apple iPhone 16',
    description:
      'Flagship smartphone with A16 Bionic chip, expansive OLED display, and advanced camera system.',
    deliveryPeriod: '1–2 days',
    specs: [
      'A16 Bionic 6-core CPU',
      '6.7" Super Retina XDR OLED',
      '128 GB / 256 GB storage options',
      '48 MP main camera with Night mode',
      '5G, Wi-Fi 6, Bluetooth 5.3',
      'Face ID and MagSafe charging',
    ],
    slashedPrice: '1700000',
    // discountPercent: null,
    price: '1220000',
    rating: 4,
  },
  {
    src: '/imgs/ps5.png',
    title: 'PS5 Game Console',
    description:
      'Next-gen gaming console delivering ultra-high-speed SSD loading and stunning visuals.',
    deliveryPeriod: '2–4 days',
    specs: [
      'Custom AMD Ryzen Zen 2 8-core CPU',
      'Custom AMD RDNA 2 GPU (10.28 TFLOPs)',
      '825 GB NVMe SSD',
      'Up to 8K output, 4K/120 Hz support',
      'DualSense wireless controller',
      'Tempest 3D AudioTech',
    ],
    slashedPrice: '900000',
    // discountPercent: null,
    price: '720000',
    rating: 5,
  },
  {
    src: '/imgs/jblhead.png',
    title: 'JBL Headset',
    description:
      'Wireless over-ear headset featuring active noise cancellation and rich JBL audio.',
    deliveryPeriod: '1–3 days',
    specs: [
      'Bluetooth 5.0 connectivity',
      'Active Noise Cancelling (ANC)',
      'Up to 20 hours battery life',
      'Foldable design for portability',
      'Built-in microphone for calls',
      'Comfort-fit ear cushions',
    ],
    slashedPrice: '100000',
    // discountPercent: null,
    price: '70000',
    rating: 4,
  },
  {
    src: '/imgs/watchX6Pro.png',
    title: 'Smartwatch X6Pro',
    description:
      'Feature-rich smartwatch with health tracking, GPS, and long battery life.',
    deliveryPeriod: '1–2 days',
    specs: [
      '1.78" AMOLED touchscreen',
      'Heart rate & SpO₂ monitoring',
      'Built-in GPS & GLONASS',
      'Sleep and stress tracking',
      'Up to 7 days battery life',
      'IP68 water & dust resistance',
    ],
    slashedPrice: '300000',
    // discountPercent: null,
    price: '220000',
    rating: 4,
  },
  {
    src: '/imgs/iPhone12promax.png',
    title: 'Apple IPhone 12 Pro Max',
    description:
      'Large-screen flagship with A14 Bionic chip, triple-lens camera array, and LiDAR scanner.',
    deliveryPeriod: '2–4 days',
    specs: [
      '6.7" Super Retina XDR OLED',
      'A14 Bionic 6-core CPU',
      'Triple 12 MP cameras (wide, ultra-wide, telephoto)',
      'LiDAR scanner for improved AR',
      '5G / Wi-Fi 6 / Bluetooth 5.0',
      'Up to 20h video playback',
    ],
    slashedPrice: '700000',
    discountPercent: '-40%',
    price: '420000',
    rating: 4,
  },
  {
    src: '/imgs/keyboard.png',
    title: 'AK-900 Wired Keyboard',
    description:
      'Mechanical USB keyboard with clicky blue switches and per-key RGB lighting.',
    deliveryPeriod: '1–2 days',
    specs: [
      'Outemu Blue mechanical switches',
      'N-key rollover for anti-ghosting',
      'Detachable braided USB-C cable',
      'Per-key customizable RGB backlight',
      'Aluminum top plate',
      'Adjustable tilt legs',
    ],
    slashedPrice: '12000',
    discountPercent: '-35%',
    price: '7800',
    rating: 3,
  },
  {
    src: '/imgs/mcbookair.png',
    title: 'Apple MacBook Air',
    description:
      'Ultra-thin laptop powered by Apple M1, with Retina display and all-day battery life.',
    deliveryPeriod: '2–4 days',
    specs: [
      'Apple M1 chip with 8-core CPU/GPU',
      '13.3" Retina display (2560×1600)',
      '8 GB unified RAM',
      '256 GB SSD storage',
      'Magic Keyboard & Touch ID',
      'Up to 18h battery life',
    ],
    slashedPrice: '870000',
    discountPercent: '-30%',
    price: '609000',
    rating: 4,
  },
  {
    src: '/imgs/iPhone11.png',
    title: 'Apple IPhone 11',
    description:
      'Durable smartphone with A13 Bionic, dual-camera system, and long battery life.',
    deliveryPeriod: '1–2 days',
    specs: [
      '6.1" Liquid Retina LCD',
      'A13 Bionic chip',
      'Dual 12 MP cameras (wide & ultra-wide)',
      'Face ID & IP68 water resistance',
      'Up to 17h video playback',
      'Wireless charging',
    ],
    slashedPrice: '500000',
    discountPercent: '-25%',
    price: '375000',
    rating: 2,
  },
  {
    src: '/imgs/pad.png',
    title: 'HAVIT HV-G92 Gamepad',
    description:
      'Ergonomic wired controller with dual vibration motors for PC and consoles.',
    deliveryPeriod: '1–2 days',
    specs: [
      'USB-A connection (plug-and-play)',
      'Dual vibration feedback',
      '6-axis gyroscope support',
      'Adjustable trigger sensitivity',
      'Comfort-fit rubber grips',
    ],
    slashedPrice: '14000',
    discountPercent: '-40%',
    price: '8400',
    rating: 4,
  },
  {
    src: '/imgs/redmi.png',
    title: 'Redmi Note 13',
    description:
      'Feature-packed mid-range phone with AMOLED display and quad-camera setup.',
    deliveryPeriod: '2–3 days',
    specs: [
      '6.67" AMOLED, 120 Hz',
      'MediaTek Dimensity 6080 processor',
      '6 GB RAM, 128 GB storage',
      '50 MP main + 8 MP ultra-wide + 2 MP macro + 2 MP depth',
      '5000 mAh battery with 33 W fast charge',
      'Side-mounted fingerprint sensor',
    ],
    slashedPrice: '400000',
    discountPercent: '-35%',
    price: '260000',
    rating: 3,
  },
  {
    src: '/imgs/tv.png',
    title: 'IPS LCD Gaming Monitor',
    description:
      '24" gaming monitor with IPS panel, 144 Hz refresh rate, and 1 ms response time.',
    deliveryPeriod: '3–5 days',
    specs: [
      '24" 1080p IPS display',
      '144 Hz refresh rate',
      '1 ms MPRT response time',
      'AMD FreeSync support',
      'Height-adjustable stand',
      'VESA mount compatible',
    ],
    slashedPrice: '150000',
    discountPercent: '-30%',
    price: '105000',
    rating: 4,
  },
  {
    src: '/imgs/iPhonexr.png',
    title: 'Apple IPhone XR',
    description:
      'Colorful iPhone with Liquid Retina display, A12 Bionic chip, and reliable performance.',
    deliveryPeriod: '1–2 days',
    specs: [
      '6.1" Liquid Retina LCD',
      'A12 Bionic chip',
      'Single 12 MP wide camera',
      'Face ID & IP67 water resistance',
      'Up to 15h video playback',
      'Multiple vibrant color options',
    ],
    slashedPrice: '350000',
    discountPercent: '-25%',
    price: '262500',
    rating: 2,
  },
];
