import type { Metadata } from 'next';
import { Poppins, Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/app-layout/Header';

const poppins = Poppins({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

const inter = Inter({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable} antialiased`}>
        <aside className="fixed top-0 left-0 right-0 text-[12px] md:text-[14px] z-10 flex items-center justify-center gap-3 bg-black p-4 text-mainWhite h-[3rem]">
          <p>
            {' '}
            Promo Sale For All Phones and Free Express Delivery - OFF 50%!{' '}
          </p>
          <span className="underline"> ShopNow</span>
        </aside>
        <Header />
        {children}
      </body>
    </html>
  );
}
